### ISSUE TITLE
Can I input data generate from networkx

### ISSUE THREAD

**Issue by dick2737** [ThanasisMattas/shortestpaths#1]
I want to input my own data generate from networkx, maybe you can add an parameter for the options

**Comment by ThanasisMattas** [comment]
Hello! Thanks for the great suggestion. Please install the latest version and try your graph using the command:

```bash
ksp -v -s <source> -t <target> -k <num_paths> --path <path-to_graph>
```
* Use the ```--directed``` flag if your graph is directed.
* Also, you can use ```--show-graph```  and/or ```--save-graph``` to visualise your graph and the paths generated (first 8 paths), if it is not too big.

Find more info [here](https://github.com/ThanasisMattas/shortestpaths#usage).

Thanks again.
